apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rabbitmq-test-cluster01
  namespace: rabbitmq
spec:
  path: /
  to:
    name: rabbitmq-test-cluster01
    weight: 100
    kind: Service
  tls: null
  port:
    targetPort: management
