apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-test-cluster01
  namespace: rabbitmq
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "*"
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 500m
      memory: 2Gi
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            securityContext: {}
  service:
    type: ClusterIP
  tls: {}
  image: 'rabbitmq:4.1.3-management'
  rabbitmq: 
    additionalConfig: |
      auth_backends.1 = rabbit_auth_backend_oauth2
      management.oauth_enabled = true
      management.oauth_client_id = rabbitmq-proxy-client
      management.oauth_scopes = openid profile rabbitmq.tag:administrator
      auth_oauth2.resource_server_id = rabbitmq
      auth_oauth2.preferred_username_claims.1 = user_name
      auth_oauth2.additional_scopes_key = extra_scope
      auth_oauth2.issuer = https://keycloak-keycloak.epical-test-35478b8a1f2793ad207bc2eca8dccf01-i000.eu-de.containers.appdomain.cloud/auth/realms/test/
  additionalPlugins:
    - rabbitmq_management
    - rabbitmq_auth_backend_oauth2

  
  replicas: 3
  rabbitmq: {}
  persistence:
    storage: 10Gi
